version: '3.8'

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:16-alpine
    container_name: todo-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tododb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker
    networks:
      - todo-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: todo-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - todo-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todo-backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tododb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - todo-net

  frontend:
    build:
     context: ./frontend
     dockerfile: Dockerfile
    container_name: todo-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - todo-net

networks:
  todo-net: